global_options:
  freezed:
    runs_before:
      - riverpod_generator
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator
targets:
  $default:
    builders:
      freezed:
        generate_for:
          - "lib/src/features/**/data/models/**.dart"
          - "lib/src/service/state/default_state.dart"
          - "lib/models/**.dart"
      retrofit_generator:
        generate_for:
          - "lib/src/features/**/data/datasource/**.dart"
          - "lib/data/**/**.dart"
      auto_route_generator:
        generate_for:
          - "lib/src/features/**/presentation/**/page.dart"
          - "lib/src/router/router.dart"
          - "lib/views/router.dart"
          - "lib/views/**/**.dart"
      riverpod_generator:
        generate_for:
          - "lib/src/features/**/application/**.dart"
          - "lib/controllers/**.dart"
